#!/usr/bin/env python3
from __future__ import annotations
import asyncio,sys,tempfile,unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT/'server'))
from edge1_snmp_platform import add_device,connect_db
from edge1_snmp_services import AlertEngine,DiscoveryService,MIBService,add_topology_link,ensure_extended_schema,get_topology,parse_integer,search_all,sync_interfaces
class FakeNet:
 def query(self,tool,address,port,profile_ref,oids,**kwargs):
  if tool=='snmpget': return {oids[0]:'router desc',oids[1]:'router-01',oids[2]:'1.3.6.1.4.1.9',oids[3]:'lab',oids[4]:'noc'}
  return {}
class ServiceTests(unittest.TestCase):
 def setUp(self): self.tmp=tempfile.TemporaryDirectory(); self.conn=connect_db(Path(self.tmp.name)/'x.db'); ensure_extended_schema(self.conn); self.device=add_device(self.conn,{'display_name':'router-01','management_address':'10.10.1.1','credential_reference':'r-v3'})
 def tearDown(self): self.conn.close(); self.tmp.cleanup()
 def test_interface_sync_and_search(self):
  sync_interfaces(self.conn,self.device['device_id'],[{'if_index':1,'if_name':'eth0','if_descr':'uplink','if_alias':'core','if_type':6,'admin_status':1,'oper_status':2,'speed_bps':1000000000,'counters':{'ifHCInOctets':100}}]); self.assertEqual(search_all(self.conn,'uplink')['interfaces'][0]['if_index'],1)
 def test_alert_engine_dedupes_open_alerts(self):
  self.conn.execute("UPDATE devices SET status='offline',last_error='authentication failure' WHERE device_id=?",(self.device['device_id'],)); self.conn.commit(); first=AlertEngine(self.conn).evaluate(); second=AlertEngine(self.conn).evaluate(); self.assertGreaterEqual(first['count'],2); self.assertEqual(self.conn.execute("SELECT count(*) FROM alerts WHERE state='open'").fetchone()[0],2); self.assertGreaterEqual(second['count'],2)
 def test_mib_lookup(self):
  svc=MIBService(self.conn); svc.upsert_object(oid='1.3.6.1.2.1.1.3.0',name='sysUpTime',module='SNMPv2-MIB',description='uptime'); self.assertEqual(svc.lookup('sysUpTime')['oid'],'1.3.6.1.2.1.1.3.0'); self.assertEqual(len(svc.search('uptime')),1)
 def test_topology_evidence(self):
  link=add_topology_link(self.conn,local_device_id=self.device['device_id'],local_if_index=1,remote_device_id=None,remote_identifier='switch-01',remote_port='Gi1/0/1',evidence_type='LLDP',confidence='confirmed',evidence={'oid':'lldpRemSysName'}); topo=get_topology(self.conn); self.assertEqual(topo['links'][0]['link_id'],link); self.assertEqual(topo['links'][0]['confidence'],'confirmed')
 def test_discovery_preview_is_bounded(self):
  cfg={'polling':{'interval_seconds':300,'concurrency':4},'discovery':{'allowed_cidrs':['10.10.0.0/16'],'max_hosts':32,'allow_public':False}}; result=asyncio.run(DiscoveryService(FakeNet()).scan('10.10.2.0/30','profile',config=cfg,dry_run=True)); self.assertEqual(result['count'],2)
 def test_discovery_probe(self):
  cfg={'polling':{'interval_seconds':300,'concurrency':4},'discovery':{'allowed_cidrs':['10.10.0.0/16'],'max_hosts':32,'allow_public':False}}; result=asyncio.run(DiscoveryService(FakeNet()).scan('10.10.2.0/30','profile',config=cfg,dry_run=False)); self.assertTrue(all(x['snmp_capable'] for x in result['devices']))
 def test_parse_integer(self): self.assertEqual(parse_integer('INTEGER: up(1)'),1)
 def test_snmp_status_publication_is_scoped(self):
  service=(ROOT/'deploy'/'edge1-snmp-poller.service').read_text(encoding='utf-8'); installer=(ROOT/'deploy'/'install-edge1-snmp.sh').read_text(encoding='utf-8'); page=(ROOT/'src'/'web'/'operations-center'/'snmp.html').read_text(encoding='utf-8'); exporter=(ROOT/'server'/'operations_snmp_exporter.py').read_text(encoding='utf-8'); target='/var/www/edge1-status/snmp/operations-snmp.json'; self.assertIn(f'EDGE1_SNMP_STATUS_OUTPUT={target}',service); self.assertIn('ReadWritePaths=/var/lib/edge1-snmp /var/www/edge1-status/snmp',service); self.assertNotIn('ReadWritePaths=/var/lib/edge1-snmp /var/www/edge1-status\n',service); self.assertIn('install -d -o wwadmin -g wwadmin -m 0755 "$STATUS_DIR"',installer); self.assertIn(target,exporter); self.assertIn('../snmp/operations-snmp.json',page)
 def test_snmp_ai_identity_uses_transient_systemd_credentials(self):
  api=(ROOT/'deploy'/'edge1-snmp-api.service').read_text(encoding='utf-8'); identity=(ROOT/'deploy'/'edge1-snmp-ai-identity.service').read_text(encoding='utf-8'); projector=(ROOT/'deploy'/'prepare-edge1-snmp-ai-credentials.sh').read_text(encoding='utf-8'); installer=(ROOT/'deploy'/'install-edge1-snmp.sh').read_text(encoding='utf-8'); self.assertIn('Requires=edge1-snmp-ai-identity.service',api); self.assertIn('LoadCredential=bb_relay_key_id:/run/edge1-snmp-ai-identity/bb_relay_key_id',api); self.assertIn('LoadCredential=bb_relay_secret:/run/edge1-snmp-ai-identity/bb_relay_secret',api); self.assertNotIn('EnvironmentFile=/etc/bigbird-ai-gateway.env',api); self.assertIn('RuntimeDirectory=edge1-snmp-ai-identity',identity); self.assertIn('ExecStart=/usr/local/libexec/edge1-snmp/prepare-edge1-snmp-ai-credentials.sh',identity); self.assertIn('ReadOnlyPaths=/usr/local/libexec/edge1-snmp /etc/bigbird-ai-gateway.env',identity); self.assertNotIn('ExecStart=/opt/edge1-management-interface/',identity); self.assertIn('BB_RELAY_KEY_ID',projector); self.assertIn('BB_RELAY_SECRET',projector); self.assertNotIn('OPENAI_API_KEY',projector); self.assertNotIn('WWCX_MESSAGING_CONTROL_TOKEN',projector); self.assertIn('install -d -o root -g root -m 0755 "$LIBEXEC_DIR"',installer); self.assertIn('install -o root -g root -m 0755 "$ROOT/deploy/prepare-edge1-snmp-ai-credentials.sh" "$LIBEXEC_DIR/prepare-edge1-snmp-ai-credentials.sh"',installer); self.assertIn('edge1-snmp-ai-identity.service',installer)
 def test_snmp_runtime_is_decoupled_from_shared_checkout(self):
  runtime='/usr/local/libexec/edge1-snmp'; installer=(ROOT/'deploy'/'install-edge1-snmp.sh').read_text(encoding='utf-8'); units=[(ROOT/'deploy'/name).read_text(encoding='utf-8') for name in ('edge1-snmp-api.service','edge1-snmp-poller.service','edge1-snmp-actions.service')]; self.assertIn('for source in "$ROOT"/server/edge1_snmp_*.py "$ROOT/server/operations_snmp_exporter.py"',installer); self.assertIn('install -o root -g root -m 0644 "$source" "$LIBEXEC_DIR/$(basename "$source")"',installer); self.assertIn('/usr/bin/python3 "$LIBEXEC_DIR/edge1_snmp_platform.py" init-db',installer); [self.assertIn(f'WorkingDirectory={runtime}',unit) for unit in units]; [self.assertNotIn('/opt/edge1-management-interface/server',unit) for unit in units]; self.assertIn(f'ExecStart=/usr/bin/python3 {runtime}/edge1_snmp_api.py',units[0]); self.assertIn(f'ExecStart=/usr/bin/python3 {runtime}/edge1_snmp_cycle.py',units[1]); self.assertIn(f'ExecStart=/usr/bin/python3 {runtime}/edge1_snmp_action_runner.py',units[2])
if __name__=='__main__': unittest.main(verbosity=2)
