(()=>{'use strict';
const $=id=>document.getElementById(id); let modules=[], selected=null;
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
async function api(path,opts={}){const r=await fetch('/edge1-ops/navigation-admin/api'+path,{credentials:'same-origin',cache:'no-store',...opts,headers:{'Accept':'application/json',...(opts.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||`HTTP ${r.status}`);return j}
function notice(text,bad=false){$('notice').textContent=text;$('notice').style.borderColor=bad?'#e3b3ae':'#c7ddea';}
function renderRows(){const q=$('search').value.trim().toLowerCase();const tbody=$('rows');tbody.replaceChildren();for(const m of modules.filter(x=>(x.label+' '+x.section+' '+x.id).toLowerCase().includes(q))){const tr=document.createElement('tr');if(selected&&selected.id===m.id)tr.className='selected';tr.innerHTML=`<td><input class="toggle" type="checkbox" ${m.enabled?'checked':''} aria-label="${esc(m.label)} active"></td><td><strong>${esc(m.label)}</strong><br><span class="muted">${esc(m.id)}</span></td><td>${esc(m.section)}</td><td>${esc(m.icon||'circle')}</td><td class="route" title="${esc(m.browser_route||'')}">${esc(m.browser_route||'—')}</td><td>${esc(m.theme)}</td><td>${m.sort_order}</td><td><span class="pill ${m.availability==='accepted_live'?'live':''}">${esc(m.availability)}</span></td>`;
const box=tr.querySelector('input');box.addEventListener('click',async e=>{e.stopPropagation();try{await savePatch(m,{enabled:box.checked});}catch(err){box.checked=!box.checked;notice(err.message,true)}});tr.addEventListener('click',()=>{selected=m;renderRows();renderEditor();});tbody.append(tr)}renderPreview()}
function renderPreview(){const root=$('preview');root.replaceChildren();const enabled=modules.filter(m=>m.enabled&&m.menu_visibility!=='hidden').sort((a,b)=>a.sort_order-b.sort_order);for(const section of [...new Set(enabled.map(m=>m.section))]){const g=document.createElement('div');g.className='preview-group';const h=document.createElement('strong');h.textContent=section;g.append(h);for(const m of enabled.filter(x=>x.section===section)){const d=document.createElement('div');d.className='preview-item'+(selected&&selected.id===m.id?' current':'');d.innerHTML=`<span>${esc(m.label)}</span><small>${esc(m.icon||'circle')} · ${esc(m.theme)}</small>`;g.append(d)}root.append(g)}}
function renderEditor(){const root=$('editor');if(!selected){root.innerHTML='<h2>Edit module</h2><p class="muted">Choose a menu item.</p>';return}const m=selected;root.innerHTML=`<h2>${esc(m.label)}</h2><p class="muted">${esc(m.id)} · authorization: ${esc(m.authorization)}</p><form id="editform"><div class="editor-grid"><label>Label<input name="label" value="${esc(m.label)}" maxlength="160"></label><label>Section<input name="section" value="${esc(m.section)}" maxlength="120"></label><label>Order<input name="sort_order" type="number" min="0" max="10000" value="${m.sort_order}"></label><label>Theme<select name="theme"><option>inherit</option><option>light</option><option>dark</option></select></label><label>Icon<select name="icon"><option>backup</option><option>bitcoin</option><option>brain</option><option>change</option><option>circle</option><option>clock</option><option>contacts</option><option>cookie</option><option>dns</option><option>firewall</option><option>history</option><option>home</option><option>link</option><option>mail</option><option>mail-shield</option><option>messages</option><option>navigation</option><option>network</option><option>newspaper</option><option>phone-book</option><option>phone-call</option><option>pickaxe</option><option>release</option><option>route</option><option>settings</option><option>shield</option><option>sms</option><option>sparkles</option></select></label><label>Visibility<select name="menu_visibility"><option>primary</option><option>live</option><option>upcoming</option><option>hidden</option></select></label><label class="wide">Browser route<input name="browser_route" value="${esc(m.browser_route||'')}" placeholder="No accepted browser route"></label><label class="wide">Description<textarea name="description" rows="3" maxlength="1000">${esc(m.description||'')}</textarea></label></div><div class="checks"><label><input name="enabled" type="checkbox" ${m.enabled?'checked':''}> Active</label><label><input name="dashboard_visibility" type="checkbox" ${m.dashboard_visibility?'checked':''}> Dashboard</label><label><input name="toolbox" type="checkbox" ${m.toolbox?'checked':''}> ToolBox</label><label><input name="palette" type="checkbox" ${m.palette?'checked':''}> Jump/search</label></div><div class="warning">Changing a browser route requires explicit confirmation because links are security-sensitive navigation metadata. Navigation still does not grant authorization.</div><div class="actions"><button type="button" id="cancel">Reset</button><button class="primary" type="submit">Save changes</button></div></form>`;
const f=$('editform');f.theme.value=m.theme;f.icon.value=m.icon||'circle';f.menu_visibility.value=m.menu_visibility;$('cancel').onclick=()=>renderEditor();f.onsubmit=async e=>{e.preventDefault();const route=f.browser_route.value.trim()||null;const patch={label:f.label.value,section:f.section.value,sort_order:Number(f.sort_order.value),theme:f.theme.value,icon:f.icon.value,menu_visibility:f.menu_visibility.value,browser_route:route,description:f.description.value,enabled:f.enabled.checked,dashboard_visibility:f.dashboard_visibility.checked,toolbox:f.toolbox.checked,palette:f.palette.checked};if(route!==(m.browser_route||null)){if(!confirm(`Change route for ${m.label}?\n\n${m.browser_route||'(none)'} → ${route||'(none)'}`))return;patch.confirm_route_change=true}try{await savePatch(m,patch);notice(`Saved ${m.label}. The shared rail was regenerated.`)}catch(err){notice(err.message,true)}}}
async function savePatch(m,patch){await api('/modules/'+encodeURIComponent(m.id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});await load();selected=modules.find(x=>x.id===m.id)||null;renderRows();renderEditor()}
async function load(){const [a,b]=await Promise.all([api('/modules'),api('/audit?limit=20')]);modules=a.modules;const audit=$('audit');audit.replaceChildren();for(const x of b.audit){const d=document.createElement('div');d.className='audit-row';d.innerHTML=`<span>${esc(x.created_at)}</span><strong>${esc(x.module_id)}</strong><span>${esc((x.changed_fields||[]).join(', '))}</span>`;audit.append(d)}renderRows();if(selected)selected=modules.find(x=>x.id===selected.id)||null}
$('search').addEventListener('input',renderRows);$('refresh').onclick=()=>load().then(()=>notice('Navigation registry refreshed.')).catch(e=>notice(e.message,true));
load().then(()=>notice('Database-backed navigation registry ready.')).catch(e=>notice(e.message,true));
})();
