#!/usr/bin/env python3
"""Private visual generation for Ava's browser worker.

Uses the existing Edge1 OPENAI_API_KEY and the existing signed browser-worker
identity. Generated bytes are returned only to the authenticated WW.CX private
asset store; no image bytes or provider credential enter the browser queue JSON.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import json
import mimetypes
import os
import secrets
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Any

OPENAI_IMAGE_MODEL = os.environ.get("BB_OPENAI_IMAGE_MODEL", "gpt-image-2").strip() or "gpt-image-2"
OPENAI_API_URL = "https://api.openai.com/v1/images/generations"
OPENAI_EDIT_URL = "https://api.openai.com/v1/images/edits"
ASSET_URL = "https://ww.cx/api/ava-visual-asset.php"
STORE_URL = "https://ww.cx/api/ava-visual-store.php"
MAX_IMAGE_BYTES = 12 * 1024 * 1024
ALLOWED_MODES = {"image", "clipart", "diagram", "edit"}
ALLOWED_SIZES = {"1024x1024", "1536x1024", "1024x1536"}


class VisualError(RuntimeError):
    pass


@dataclass(frozen=True)
class HttpResult:
    status: int
    headers: dict[str, str]
    body: bytes


def _sha256(body: bytes) -> str:
    return hashlib.sha256(body).hexdigest()


def _http(request: urllib.request.Request, timeout: float, limit: int) -> HttpResult:
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            body = response.read(limit + 1)
            if len(body) > limit:
                raise VisualError("HTTP response exceeded the configured size limit")
            return HttpResult(int(response.status), {k.lower(): v for k, v in response.headers.items()}, body)
    except urllib.error.HTTPError as exc:
        body = exc.read(limit + 1)
        if len(body) > limit:
            raise VisualError("HTTP error response exceeded the configured size limit") from exc
        return HttpResult(int(exc.code), {k.lower(): v for k, v in exc.headers.items()}, body)
    except urllib.error.URLError as exc:
        raise VisualError(f"HTTP transport unavailable: {type(exc.reason).__name__}") from exc


def _wwcx_headers(method: str, url: str, body: bytes, secret: str, key_id: str) -> tuple[dict[str, str], str]:
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme != "https" or parsed.hostname != "ww.cx" or parsed.port is not None:
        raise VisualError("visual asset URL must remain exactly on https://ww.cx")
    if parsed.path not in {"/api/ava-visual-asset.php", "/api/ava-visual-store.php"}:
        raise VisualError("visual asset URL path is not approved")
    uri = parsed.path + (f"?{parsed.query}" if parsed.query else "")
    timestamp = str(int(time.time()))
    nonce = secrets.token_hex(16)
    digest = _sha256(body)
    canonical = f"{method}\n{uri}\n{timestamp}\n{nonce}\n{digest}"
    signature = hmac.new(secret.encode(), canonical.encode(), hashlib.sha256).hexdigest()
    return ({
        "X-BB-Worker-Key-ID": key_id,
        "X-BB-Timestamp": timestamp,
        "X-BB-Nonce": nonce,
        "X-BB-Body-SHA256": digest,
        "X-BB-Signature": signature,
        "User-Agent": "wwcx-ava-visual-worker/1",
    }, nonce)


def _verify_wwcx_response(result: HttpResult, nonce: str, secret: str) -> None:
    timestamp = result.headers.get("x-bb-response-timestamp", "")
    digest = result.headers.get("x-bb-response-body-sha256", "")
    signature = result.headers.get("x-bb-response-signature", "")
    if not timestamp or not digest or not signature:
        raise VisualError(f"visual endpoint returned unsigned HTTP {result.status}")
    if not hmac.compare_digest(digest, _sha256(result.body)):
        raise VisualError("visual endpoint body hash mismatch")
    canonical = f"{result.status}\n{timestamp}\n{nonce}\n{digest}"
    expected = hmac.new(secret.encode(), canonical.encode(), hashlib.sha256).hexdigest()
    if not hmac.compare_digest(signature, expected):
        raise VisualError("visual endpoint response signature mismatch")


def _fetch_source(user_hash: str, kind: str, asset_id: str, secret: str, key_id: str) -> tuple[bytes, str]:
    query = urllib.parse.urlencode({"user": user_hash, "kind": kind, "id": asset_id})
    url = f"{ASSET_URL}?{query}"
    headers, nonce = _wwcx_headers("GET", url, b"", secret, key_id)
    result = _http(urllib.request.Request(url, method="GET", headers=headers), 30.0, MAX_IMAGE_BYTES)
    _verify_wwcx_response(result, nonce, secret)
    if result.status != 200:
        raise VisualError("visual source is unavailable")
    mime = result.headers.get("content-type", "").split(";", 1)[0].strip().lower()
    if mime not in {"image/png", "image/jpeg", "image/webp", "image/gif"}:
        raise VisualError("visual source has an unsupported image type")
    return result.body, mime


def _prompt(mode: str, prompt: str) -> str:
    prompt = prompt.strip()
    if not prompt or len(prompt) > 8000:
        raise VisualError("visual prompt is empty or too long")
    if mode == "clipart":
        return "Create reusable clip art with a clean isolated subject, crisp edges, simple readable shapes, no watermark, and a transparent background. " + prompt
    if mode == "diagram":
        return "Create a clear professional explanatory diagram. Prioritize legible labels, visual hierarchy, clean spacing, and factual relationships. " + prompt
    if mode == "edit":
        return "Edit the supplied image according to this instruction while preserving unrelated content unless the instruction requires changing it: " + prompt
    return prompt


def _json_openai(url: str, payload: dict[str, Any], api_key: str) -> dict[str, Any]:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode()
    request = urllib.request.Request(url, data=body, method="POST", headers={
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "User-Agent": "wwcx-ava-visual-worker/1",
    })
    result = _http(request, 180.0, 20 * 1024 * 1024)
    try:
        decoded = json.loads(result.body.decode("utf-8")) if result.body else {}
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise VisualError(f"image provider returned unreadable HTTP {result.status}") from exc
    if result.status < 200 or result.status >= 300:
        raise VisualError(f"image provider rejected request with HTTP {result.status}")
    if not isinstance(decoded, dict):
        raise VisualError("image provider returned an invalid response")
    return decoded


def _multipart(fields: dict[str, str], image: bytes, mime: str) -> tuple[bytes, str]:
    boundary = "----wwcxava" + secrets.token_hex(12)
    chunks: list[bytes] = []
    for name, value in fields.items():
        chunks.extend([f"--{boundary}\r\n".encode(), f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode(), value.encode(), b"\r\n"])
    ext = mimetypes.guess_extension(mime) or ".png"
    chunks.extend([f"--{boundary}\r\n".encode(), f'Content-Disposition: form-data; name="image"; filename="source{ext}"\r\n'.encode(), f"Content-Type: {mime}\r\n\r\n".encode(), image, b"\r\n", f"--{boundary}--\r\n".encode()])
    return b"".join(chunks), boundary


def _edit_openai(prompt: str, size: str, source: bytes, mime: str, api_key: str) -> dict[str, Any]:
    body, boundary = _multipart({"model": OPENAI_IMAGE_MODEL, "prompt": prompt, "size": size, "quality": "medium", "output_format": "png"}, source, mime)
    request = urllib.request.Request(OPENAI_EDIT_URL, data=body, method="POST", headers={
        "Authorization": f"Bearer {api_key}",
        "Content-Type": f"multipart/form-data; boundary={boundary}",
        "User-Agent": "wwcx-ava-visual-worker/1",
    })
    result = _http(request, 180.0, 20 * 1024 * 1024)
    try:
        decoded = json.loads(result.body.decode("utf-8")) if result.body else {}
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise VisualError(f"image provider returned unreadable HTTP {result.status}") from exc
    if result.status < 200 or result.status >= 300 or not isinstance(decoded, dict):
        raise VisualError(f"image provider rejected edit with HTTP {result.status}")
    return decoded


def _decode_image(response: dict[str, Any]) -> tuple[bytes, str]:
    data = response.get("data")
    if not isinstance(data, list) or not data or not isinstance(data[0], dict):
        raise VisualError("image provider returned no image")
    item = data[0]
    raw = item.get("b64_json")
    if isinstance(raw, str) and raw:
        try:
            image = base64.b64decode(raw, validate=True)
        except ValueError as exc:
            raise VisualError("image provider returned invalid base64") from exc
    elif isinstance(item.get("url"), str):
        parsed = urllib.parse.urlparse(item["url"])
        if parsed.scheme != "https":
            raise VisualError("image provider returned an unsafe image URL")
        image = _http(urllib.request.Request(item["url"], headers={"User-Agent": "wwcx-ava-visual-worker/1"}), 60.0, MAX_IMAGE_BYTES).body
    else:
        raise VisualError("image provider returned no usable image data")
    if not image or len(image) > MAX_IMAGE_BYTES:
        raise VisualError("generated image is empty or too large")
    if image.startswith(b"\x89PNG\r\n\x1a\n"):
        return image, "image/png"
    if image.startswith(b"\xff\xd8\xff"):
        return image, "image/jpeg"
    if image.startswith(b"RIFF") and image[8:12] == b"WEBP":
        return image, "image/webp"
    raise VisualError("generated image format is unsupported")


def _store(image: bytes, mime: str, metadata: dict[str, Any], secret: str, key_id: str) -> dict[str, Any]:
    meta = json.dumps(metadata, ensure_ascii=False, separators=(",", ":")).encode()
    if len(meta) > 16384:
        raise VisualError("visual metadata is too large")
    body = b"AVAV1\n" + f"{len(meta):08x}".encode() + b"\n" + meta + image
    headers, nonce = _wwcx_headers("POST", STORE_URL, body, secret, key_id)
    headers["Content-Type"] = "application/octet-stream"
    result = _http(urllib.request.Request(STORE_URL, data=body, method="POST", headers=headers), 60.0, 512 * 1024)
    _verify_wwcx_response(result, nonce, secret)
    try:
        decoded = json.loads(result.body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise VisualError("visual store returned invalid JSON") from exc
    if result.status != 201 or not isinstance(decoded, dict) or not isinstance(decoded.get("visual"), dict):
        raise VisualError("visual store rejected generated image")
    return decoded["visual"]


def process_visual(payload: dict[str, Any], queue_secret: str, queue_key_id: str) -> dict[str, Any]:
    request_id = str(payload.get("request_id", ""))
    user = payload.get("user")
    visual = payload.get("visual_request")
    if not request_id or not isinstance(user, dict) or not isinstance(visual, dict):
        raise VisualError("visual request is incomplete")
    scopes = user.get("scopes") if isinstance(user.get("scopes"), list) else []
    if "visual:create" not in scopes:
        raise VisualError("visual:create scope is required")
    mode = str(visual.get("mode", ""))
    size = str(visual.get("size", "1024x1024"))
    if mode not in ALLOWED_MODES or size not in ALLOWED_SIZES:
        raise VisualError("visual request is invalid")
    if mode == "edit" and "visual:edit" not in scopes:
        raise VisualError("visual:edit scope is required")
    user_hash = str(user.get("id", ""))
    if len(user_hash) != 64 or any(c not in "0123456789abcdef" for c in user_hash):
        raise VisualError("visual user identifier is invalid")
    prompt = _prompt(mode, str(payload.get("message", "")))
    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        raise VisualError("OPENAI_API_KEY is not available to the visual worker")
    parent_kind = ""
    parent_id = ""
    if mode == "edit":
        parent_kind = str(visual.get("source_kind", ""))
        parent_id = str(visual.get("source_id", ""))
        if parent_kind not in {"attachment", "visual"}:
            raise VisualError("edit source kind is invalid")
        source, source_mime = _fetch_source(user_hash, parent_kind, parent_id, queue_secret, queue_key_id)
        response = _edit_openai(prompt, size, source, source_mime, api_key)
    else:
        provider_payload: dict[str, Any] = {"model": OPENAI_IMAGE_MODEL, "prompt": prompt, "size": size, "quality": "medium", "output_format": "png", "n": 1}
        if mode == "clipart":
            provider_payload["background"] = "transparent"
        response = _json_openai(OPENAI_API_URL, provider_payload, api_key)
    image, mime = _decode_image(response)
    stored = _store(image, mime, {
        "user_hash": user_hash,
        "request_id": request_id,
        "mode": mode,
        "model": OPENAI_IMAGE_MODEL,
        "prompt": str(payload.get("message", ""))[:8000],
        "mime": mime,
        "parent_kind": parent_kind,
        "parent_id": parent_id,
    }, queue_secret, queue_key_id)
    label = {"image": "image", "clipart": "clip art", "diagram": "diagram", "edit": "edited image"}[mode]
    return {"request_id": request_id, "answer": f"I created the {label}.", "mode": "visual-create", "visuals": [stored], "sources": [], "communications_sources": [], "telephony_sources": [], "mail_sources": []}
