(()=>{'use strict';const $=id=>document.getElementById(id);let state={};
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
async function api(path,opts={}){const r=await fetch('/edge1-ops/egress-admin/api'+path,{credentials:'same-origin',cache:'no-store',...opts,headers:{Accept:'application/json',...(opts.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||`HTTP ${r.status}`);return j}
function notice(t,b=false){$('notice').textContent=t;$('notice').style.borderColor=b?'#d99b97':'#dbe3ec'}
function gatewayByPool(pool){return (state.gateways?.gateways||[]).find(g=>g.pool===pool&&g.healthy)}
function renderGateways(){const root=$('gateways');root.replaceChildren();for(const g of state.gateways?.gateways||[]){const d=document.createElement('article');d.className='gateway';const cls=g.healthy?'good':g.state==='staged'||g.state==='secret_pending'?'warn':'bad';d.innerHTML=`<div class="top"><h3>${esc(g.id==='direct'?'Direct':(g.pool||g.country||g.id).toUpperCase()+' · '+(g.id.includes('secondary')?'Secondary':'Primary'))}</h3><span class="pill ${cls}">${esc(g.state)}</span></div><div class="kv"><span>Profile</span><strong>${esc(g.profile||g.interface||'Edge1')}</strong><span>Health</span><strong>${g.healthy?'Healthy':'Not active'}</strong>${g.observed_country?`<span>Observed exit</span><strong>${esc(g.observed_country)} · ${esc(g.egress_ip||'')}</strong>`:''}${Number.isFinite(g.handshake_age_seconds)?`<span>Handshake</span><strong>${g.handshake_age_seconds}s ago</strong>`:''}</div>`;root.append(d)}}
function renderServices(){const body=$('services');body.replaceChildren();const counts=state.runtime?.destination_counts||{};for(const s of state.services||[]){const tr=document.createElement('tr');const options=['direct','us','ca','mx'].map(x=>{const available=x==='direct'||!!gatewayByPool(x);return `<option value="${x}" ${s.gateway===x?'selected':''} ${!available&&s.gateway!==x?'disabled':''}>${x==='direct'?'Direct':x.toUpperCase()}${available?'':' (unavailable)'}</option>`}).join('');tr.innerHTML=`<td><input class="en" type="checkbox" ${s.enabled?'checked':''}></td><td><strong>${esc(s.label)}</strong><div class="route-note">${esc(s.description)}</div></td><td><select class="gw">${options}</select></td><td><strong>Fail closed</strong></td><td>${counts[s.id]||0}</td><td><span class="pill ${s.enabled&&s.gateway!=='direct'?'good':''}">${s.enabled?(s.gateway==='direct'?'direct':'automatic'):'disabled'}</span></td>`;for(const el of tr.querySelectorAll('input,select'))el.addEventListener('change',async()=>{try{await api('/services/'+encodeURIComponent(s.id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:tr.querySelector('.en').checked,gateway:tr.querySelector('.gw').value,fail_mode:'closed'})});notice(`Saved ${s.label}. Reconciliation requested.`);setTimeout(load,1200)}catch(e){notice(e.message,true);await load()}});body.append(tr)}}
function renderSafety(){const root=$('safety');root.replaceChildren();const rows=[['Default path',state.gateways?.default||'direct'],['Leak policy',state.gateways?.leak_policy||'fail_closed'],['Inbound commercial VPN','Denied'],['Edge1 DNS','Remains local'],['Private exclusions',(state.gateways?.private_exclusions||[]).join(', ')]];for(const [a,b] of rows){const d=document.createElement('div');d.className='safety-row';d.innerHTML=`<span class="muted">${esc(a)}</span><strong>${esc(b)}</strong>`;root.append(d)}}
async function load(){const [s,a]=await Promise.all([api('/status'),api('/audit?limit=16')]);state=s;renderGateways();renderServices();renderSafety();const root=$('audit');root.replaceChildren();for(const x of a.audit||[]){const d=document.createElement('div');d.className='audit-row';d.innerHTML=`<span>${esc(x.created_at)}</span><strong>${esc(x.service_id)}</strong><span>${esc((x.changed_fields||[]).join(', '))}</span>`;root.append(d)}notice('Live egress state loaded.')}
$('refresh').onclick=()=>load().catch(e=>notice(e.message,true));load().catch(e=>notice(e.message,true));})();
