(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let team=[],templates=[],entities=[];
async function api(p){const r=await fetch('/edge1-ops/ava-office/api/'+p,{credentials:'same-origin',cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||r.status);return j}
async function delegate(workflow_id,objective){const r=await fetch('/edge1-ops/ava-dispatch/api/workflows',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflow_id,objective})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||r.status);return j}
function badge(v,p='state'){return `<span class="badge ${p}-${esc(String(v).toLowerCase().replace(/\s+/g,'-'))}">${esc(v)}</span>`}
function metric(label,value){return `<article class="metric"><strong>${esc(value)}</strong><span>${esc(label)}</span></article>`}
function cards(id,items,fn,empty){$(id).innerHTML=items.length?items.map(fn).join(''):`<div class="card">${esc(empty)}</div>`}
function pct(v){return v===null||v===undefined?'—':Math.round(Number(v)*100)+'%'}

async function topSummary(){const x=await api('executive');const unhealthy=Object.entries(x.team_health||{}).filter(([k])=>['attention','failed','error','critical','degraded','unhealthy','warning'].includes(k)).reduce((n,[,v])=>n+v,0);$('#summary').innerHTML=metric('Team members',Object.values(x.team_health||{}).reduce((a,b)=>a+b,0))+metric('Need attention',unhealthy)+metric('Open assignments',Object.entries(x.assignments||{}).filter(([k])=>!['completed','cancelled'].includes(k)).reduce((n,[,v])=>n+v,0))+metric('Reports / 24h',x.reports_24h)+metric('Execution authority','Bounded');$('#fresh').textContent='Executive layer connected';$('#departments').innerHTML=Object.entries(x.departments||{}).map(([k,v])=>`<article class="department"><strong>${v}</strong><span>${esc(k)}</span></article>`).join('')}

async function briefing(){const x=await api('briefing'),s=x.summary||{};$('#briefingMetrics').innerHTML=metric('Workflows completed',s.workflows_completed??0)+metric('Documents new',s.documents_new??0)+metric('Contacts updated',s.contacts_updated??0)+metric('Accounting updated',s.accounting_documents_updated??0)+metric('Owner actions',s.owner_actions_required??0)+metric('Automation failures',s.automation_failures??0);const a=s.attention||[];cards('#briefingAttention',a,v=>`<article class="card"><h3>${esc(v.title)}</h3><p>${esc(v.summary)}</p><div class="meta">${badge(v.severity,'sev')}<span>${esc(v.category)}</span></div><p><strong>AVA recommendation:</strong> ${esc(v.recommended_action)}</p></article>`,s.owner_action_required?'No detailed attention records were available.':'No owner action required.')}

async function reviews(){const q=$('#ownerOnly').checked?'reviews?owner=1&state=open&limit=100':'reviews?state=open&limit=100',a=(await api(q)).items||[];cards('#reviewCards',a,v=>`<article class="card"><h3>${esc(v.title)}</h3><p>${esc(v.summary)}</p><div class="meta">${badge(v.severity,'sev')}<span>${esc(v.category)}</span><span>${esc(v.source_system)}</span>${v.owner_required?'<span>Owner required</span>':'<span>AVA may continue</span>'}</div><p><strong>Recommended:</strong> ${esc(v.recommended_action)}</p>${(v.evidence||[]).length?`<details><summary>Evidence (${v.evidence.length})</summary><ul>${v.evidence.map(e=>`<li>${esc(e)}</li>`).join('')}</ul></details>`:''}<div class="review-actions"><button type="button" data-delegate-review="${esc(v.id)}">Delegate bounded follow-up to AVA</button></div></article>`,'Nothing currently needs review.');$$('[data-delegate-review]').forEach(b=>b.onclick=()=>{const v=a.find(x=>x.id===b.dataset.delegateReview);if(!v)return;$('#delegateObjective').value=`Review and handle this bounded follow-up if an existing registered workflow applies: ${v.title}. ${v.summary} Recommended action: ${v.recommended_action}`;const tab=$('.tabs button[data-tab="workflows"]');if(tab)tab.click();loadTemplates().then(suggestTemplate).catch(()=>{})})}

function renderTeam(){const q=$('#teamSearch').value.toLowerCase();$('#teamRows').innerHTML=team.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).map(x=>`<tr><td><strong>${esc(x.display_name)}</strong><br><small>${esc(x.member_id)}</small></td><td>${esc(x.department)}</td><td>${badge(x.maturity_level)}<br><small>${esc(x.action_level)} · ceiling ${esc(x.authority_ceiling)}</small></td><td>${badge(x.health_state)}</td><td>${esc(x.run_count)}</td><td>${pct(x.success_rate)}</td><td>${esc(x.failure_count)} / ${esc(x.retry_count)}</td></tr>`).join('')}
async function loadTeam(){team=(await api('scorecards?limit=100')).items||[];renderTeam()}

function entityCard(x){const d=x.detail||{},pts=d.contact_points||[],rels=d.relationships||[],ev=d.evidence||[];const lineage=ev.slice(0,12).map(e=>`<div class="lineage-row"><span class="lineage-node"><strong>${esc(e.source_name||'Evidence source')}</strong><small>${esc(e.source_reference||'preserved source')}${e.source_page?' · page '+esc(e.source_page):''}</small></span><span class="lineage-arrow">→</span><span class="lineage-node provenance"><strong>${esc(e.verification_status||'provenance')}</strong><small>${e.source_document_id?'source document '+esc(e.source_document_id):'provenance record'}</small></span><span class="lineage-arrow">→</span><span class="lineage-node entity"><strong>${esc(x.canonical_name)}</strong><small>${esc(x.entity_type)} · ${esc(x.verification_status)}</small></span></div>`).join('');return `<article class="card"><h3>${esc(x.canonical_name)}</h3><div class="meta">${badge(x.entity_type)}${badge(x.verification_status)}${badge(x.lifecycle_status)}<span>${x.contact_points} contact points</span><span>${x.relationships} relationships</span><span>${x.document_count} documents</span><span>${x.accounting_documents} accounting docs</span></div><details><summary>Unified entity detail</summary>${pts.length?`<h4>Contact points</h4><ul>${pts.map(p=>`<li>${esc(p.point_type)} · ${esc(p.value)} · ${esc(p.assertion_type)} (${esc(p.confidence)})</li>`).join('')}</ul>`:''}${rels.length?`<h4>Relationships</h4><ul>${rels.map(r=>`<li>${esc(r.relationship_type)} · ${esc(r.related_name)} (${esc(r.confidence)})</li>`).join('')}</ul>`:''}${ev.length?`<h4>Evidence</h4><ul>${ev.map(e=>`<li>${esc(e.source_name)}${e.source_reference?' · '+esc(e.source_reference):''}${e.source_page?' · page '+esc(e.source_page):''}${e.source_document_id?' · source document '+esc(e.source_document_id):''}</li>`).join('')}</ul><h4>Provenance lineage</h4><div class="lineage">${lineage}</div>`:''}</details></article>`}
async function loadEntities(){const q=$('#entitySearch').value.trim(),path='entities?limit=100'+(q?'&q='+encodeURIComponent(q):'');entities=(await api(path)).items||[];cards('#entityCards',entities,entityCard,'No matching entities.')}

async function sources(){const a=(await api('source-health?limit=100')).items||[];cards('#sourceCards',a,v=>`<article class="card"><h3>${esc(v.name)}</h3><div class="meta">${badge(v.state)}<span>${esc(v.provider)}</span><span>last sync ${esc(v.last_sync_at_utc||'—')}</span>${v.age_hours===null?'<span>age unknown</span>':`<span>${Number(v.age_hours).toFixed(1)}h old</span>`}</div>${v.issue?`<p>${esc(v.issue)}</p>`:''}</article>`,'No source-health records.');const b=(await api('accounting-completeness?limit=100')).items||[];cards('#accountingCards',b,v=>`<article class="card"><h3>${esc(v.vendor_name)} · ${esc(v.document_kind)}</h3><div class="meta">${badge(v.state)}<span>${v.observed_periods} periods observed</span><span>${esc(v.first_period||'—')} → ${esc(v.last_period||'—')}</span></div>${(v.missing_periods||[]).length?`<p><strong>Missing:</strong> ${esc(v.missing_periods.join(', '))}</p>`:'<p>No missing periods identified from the evidence learned so far.</p>'}</article>`,'AVA is still learning recurring financial-document patterns.')}

async function loadTemplates(){templates=(await api('workflow-templates?limit=100')).items||[];const select=$('#templateSelect');select.innerHTML=templates.filter(t=>t.state==='production'&&t.workflow_id).map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('');cards('#templateCards',templates,t=>`<article class="card"><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p><div class="meta">${badge(t.state)}<span>${esc(t.category)}</span><span>owner gate: ${esc(t.owner_gate)}</span>${t.workflow_id?`<span>${esc(t.workflow_id)}</span>`:'<span>No executable workflow yet</span>'}</div>${(t.trigger_examples||[]).length?`<p><small>${esc(t.trigger_examples.join(' · '))}</small></p>`:''}</article>`,'No workflow templates registered.')}
function suggestTemplate(){const text=$('#delegateObjective').value.toLowerCase();if(!text.trim())return;let best=null,bestScore=-1;for(const t of templates.filter(x=>x.state==='production'&&x.workflow_id)){const hay=[t.name,t.category,t.description,...(t.trigger_examples||[])].join(' ').toLowerCase();const words=[...new Set(text.match(/[a-z0-9]+/g)||[])].filter(w=>w.length>3);const score=words.reduce((n,w)=>n+(hay.includes(w)?1:0),0);if(score>bestScore){bestScore=score;best=t}}if(best){$('#templateSelect').value=best.id;$('#delegateStatus').textContent=`Suggested: ${best.name}`}}
async function runSelectedTemplate(){const t=templates.find(x=>x.id===$('#templateSelect').value);if(!t||!t.workflow_id)return;const objective=$('#delegateObjective').value.trim()||t.description;$('#delegateStatus').textContent='Queuing…';try{const r=await delegate(t.workflow_id,objective);$('#delegateStatus').textContent=`Queued ${r.workflow_id}`;setTimeout(workflows,800)}catch(e){$('#delegateStatus').textContent='Failed: '+e.message}}
async function workflows(){await loadTemplates();const a=(await api('workflows?limit=100')).items||[];cards('#workflowCards',a,x=>`<article class="card"><h3>${esc(x.workflow_id)}</h3><p>${esc(x.trigger_type)} · ${esc(x.trigger_ref)}</p><div class="meta">${badge(x.state)}<span>${esc(x.requested_by)}</span><span>${esc(x.updated_at_utc)}</span></div><div class="steps">${(x.steps||[]).map(s=>`<span>${badge(s.state)} ${esc(s.step_key)} · ${esc(s.capability)} · attempts ${esc(s.attempt_count)}</span>`).join('')}</div>${x.error_summary?`<p>${esc(x.error_summary)}</p>`:''}</article>`,'No workflows have run yet.');const w=(await api('why?limit=100')).items||[];cards('#whyCards',w,x=>`<article class="card"><h3>${esc(x.trigger_text)}</h3><p><strong>Policy:</strong> ${esc(x.policy_text)}</p><p><strong>Action:</strong> ${esc(x.action_text)}</p><p><strong>Outcome:</strong> ${esc(x.outcome_text)}</p><div class="meta"><span>Owner approval: ${esc(x.owner_approval)}</span><span>${esc(x.created_at_utc)}</span></div></article>`,'No workflow explanations yet.')}

async function tools(){const x=await api('tools'),a=x.items||[];$('#toolSummary').innerHTML=metric('Advertised tools',a.filter(v=>v.kind==='tool'&&v.exposed).length)+metric('Retired / removed',a.filter(v=>['retired','removed'].includes(v.status)).length)+metric('MCP broker',x.broker?.reachable?'Healthy':'Unavailable')+metric('Gateway',x.gateway?.reachable?'Healthy':'Unavailable')+metric('Chat mutations',x.conversational_mutations?'Enabled':'Disabled')+metric('Shell exposure',x.generic_shell_exposed?'Enabled':'None');cards('#toolCards',a,v=>`<article class="card"><h3>${esc(v.name)}</h3><p>${esc(v.notes||'')}</p><div class="meta">${badge(v.status)}<span>${esc(v.kind)}</span><span>${esc(v.transport)}</span><span>${esc(v.authority)}</span>${v.exposed?'<span>Exposed to AVA</span>':'<span>Not exposed</span>'}${v.replacement?`<span>→ ${esc(v.replacement)}</span>`:''}</div></article>`,'No tools or connectors registered.')}

async function hygiene(){const a=(await api('hygiene?limit=100')).items||[];cards('#hygieneCards',a,v=>`<article class="card"><h3>${esc(v.subject)}</h3><p>${esc(v.rationale)}</p><div class="meta">${badge(v.state)}<span>${esc(v.category)}</span></div><p><strong>Recommendation:</strong> ${esc(v.recommended_action)}</p></article>`,'No hygiene findings.');const b=(await api('automation-lifecycle?limit=200')).items||[];cards('#lifecycleCards',b,v=>`<article class="card"><h3>${esc(v.object_type)} · ${esc(v.object_id)}</h3><div class="meta">${badge(v.stage)}<span>${esc(v.validation_state)}</span><span>${esc(v.version||'—')}</span></div><p>${esc(v.notes||'')}</p></article>`,'No lifecycle records.')}

async function assignments(){const a=(await api('assignments?limit=100')).items||[];cards('#assignmentCards',a,x=>`<article class="card"><h3>${esc(x.objective)}</h3><div class="meta">${badge(x.state)}<span>${esc(x.display_name)}</span><span>${esc(x.priority)} priority</span><span>${esc(x.updated_at_utc)}</span></div></article>`,'No assignments.')}
async function reports(){const q=$('#attentionOnly').checked?'reports?attention=1&limit=100':'reports?limit=100',a=(await api(q)).items||[];cards('#reportCards',a,x=>`<article class="card"><h3>${esc(x.summary)}</h3><div class="meta">${badge(x.severity,'sev')}${badge(x.health_state)}<span>${esc(x.department)}</span><span>${esc(x.created_at_utc)}</span></div></article>`,'No reports in this view.')}
async function work(){const a=(await api('work-items?limit=100')).items||[];cards('#workCards',a,x=>`<article class="card"><h3>${esc(x.title)}</h3><p>${esc(x.desired_outcome)}</p><div class="meta">${badge(x.state)}<span>${esc(x.priority)} priority</span><span>owner ${esc(x.owner)}</span></div></article>`,'No work items.')}

const loaders={briefing,reviews,team:loadTeam,entities:loadEntities,sources,workflows,tools,hygiene,assignments,reports,work};
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.tab));const fn=loaders[b.dataset.tab];if(fn)fn().catch(e=>$('#fresh').textContent='Unavailable: '+e.message)});
$('#teamSearch').oninput=renderTeam;$('#entitySearch').onchange=()=>loadEntities();$('#entitySearch').onkeydown=e=>{if(e.key==='Enter')loadEntities()};$('#attentionOnly').onchange=reports;$('#ownerOnly').onchange=reviews;$('#suggestTemplate').onclick=suggestTemplate;$('#runTemplate').onclick=runSelectedTemplate;
Promise.all([topSummary(),briefing()]).catch(e=>$('#fresh').textContent='Unavailable: '+e.message);
})();
