#!/usr/bin/env python3
"""Render local-only Postfix configuration fragments for Edge1 Mail Gateway v1.

The renderer refuses any configuration that enables public SMTP, production MX
changes, outbound delivery, or ww.cx migration. It writes templates/maps only and
never changes /etc/postfix or restarts Postfix.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_CONFIG = ROOT / "config" / "messaging" / "edge1-mail-gateway-v1.json"

DOMAIN_RE = re.compile(r"^[a-z0-9](?:[a-z0-9.-]{0,251}[a-z0-9])?$")


class RenderError(RuntimeError):
    pass


def _validate_safety(data: dict) -> None:
    if not isinstance(data, dict):
        raise RenderError("configuration must be an object")
    if data.get("contract") != "wwcx.edge1-mail-gateway.v1":
        raise RenderError("configuration contract is invalid")
    if data.get("service_hostname") != "mail.ww.cx":
        raise RenderError("service hostname must be mail.ww.cx")
    if data.get("activation") != {
        "public_smtp_listener_enabled": False,
        "production_mx_changes_authorized": False,
        "outbound_delivery_enabled": False,
    }:
        raise RenderError("renderer requires safely disabled activation state")


def _load(path: pathlib.Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    _validate_safety(data)
    return data


def _candidate_domains(data: dict) -> list[str]:
    domains = data.get("domains")
    if not isinstance(domains, dict):
        raise RenderError("domains must be an object")
    ordered: list[tuple[int, str]] = []
    for domain, entry in domains.items():
        value = str(domain).casefold()
        if not DOMAIN_RE.fullmatch(value) or ".." in value:
            raise RenderError("domain name is invalid")
        if not isinstance(entry, dict):
            raise RenderError("domain entry is invalid")
        if entry.get("mode") == "candidate":
            order = entry.get("migration_order")
            if not isinstance(order, int) or order < 1:
                raise RenderError("candidate migration order is invalid")
            if entry.get("catch_all_enabled") is not True:
                raise RenderError("candidate must have catch-all enabled")
            ordered.append((order, value))
    ordered.sort()
    result = [domain for _, domain in ordered]
    if len(result) != len(set(result)):
        raise RenderError("candidate domains are duplicated")
    if "ww.cx" in result:
        raise RenderError("ww.cx must remain external in v1")
    return result


def _regex_domain(domain: str) -> str:
    return re.escape(domain)


def render(data: dict) -> dict[str, str]:
    _validate_safety(data)
    domains = _candidate_domains(data)
    managed_domains = "".join(f"{domain} OK\n" for domain in domains)
    recipient_regexp = "".join(
        f"/^[^@[:space:]]+@{_regex_domain(domain)}$/ OK\n" for domain in domains
    )

    main_cf = "\n".join(
        [
            "# Generated by render_edge1_mail_gateway_postfix.py",
            "# LOCAL-ONLY PREPARATION: do not use as public activation evidence.",
            "inet_interfaces = loopback-only",
            "smtpd_recipient_restrictions = permit_mynetworks,reject_unauth_destination",
            "relay_domains =",
            "virtual_mailbox_domains = hash:/etc/postfix/wwcx-edge1-managed-domains",
            "virtual_mailbox_maps = regexp:/etc/postfix/wwcx-edge1-recipient-regexp",
            "virtual_transport = wwcxmail:",
            "wwcxmail_destination_recipient_limit = 1",
            "",
        ]
    )
    master_cf = "\n".join(
        [
            "# Generated by render_edge1_mail_gateway_postfix.py",
            "# LOCAL-ONLY PREPARATION: pipe accepted managed-domain mail into Mail Room.",
            "# O preserves X-Original-To; recipient limit 1 is required for exact attribution.",
            "wwcxmail unix - n n - - pipe",
            "  flags=ROq user=wwcx-mail-gateway argv=/usr/bin/python3 /opt/edge1-management-interface/tools/messaging/edge1_mail_gateway_ingest.py --stdin --recipient ${original_recipient} --queue-id ${queue_id} --store /var/lib/wwcx-mail-room/correspondence.sqlite3",
            "",
        ]
    )
    return {
        "wwcx-edge1-managed-domains": managed_domains,
        "wwcx-edge1-recipient-regexp": recipient_regexp,
        "main.cf.fragment": main_cf,
        "master.cf.fragment": master_cf,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default=str(DEFAULT_CONFIG))
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()

    try:
        data = _load(pathlib.Path(args.config))
        rendered = render(data)
        output = pathlib.Path(args.output_dir).absolute()
        if output.is_symlink():
            raise RenderError("output directory may not be a symlink")
        output.mkdir(parents=True, exist_ok=True, mode=0o755)
        for name, content in rendered.items():
            target = output / name
            if target.is_symlink():
                raise RenderError("output target may not be a symlink")
            target.write_text(content, encoding="utf-8")
        print(str(output))
        return 0
    except (OSError, ValueError, json.JSONDecodeError, RenderError) as exc:
        print(str(exc))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
