#!/bin/sh
set -eu
EDGE=${EDGE1_HIDDEN_PRIMARY_LISTEN_V4:-89.126.248.191}
for SRC in 204.13.249.65 208.78.68.65; do
  /usr/sbin/ufw allow proto tcp from "$SRC" to "$EDGE" port 53 comment 'Dyn hidden-primary AXFR/IXFR'
  /usr/sbin/ufw allow proto udp from "$SRC" to "$EDGE" port 53 comment 'Dyn hidden-primary DNS/NOTIFY'
done
